network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
        - 172.16.0.2/24
      nameservers:
        addresses: [ 8.8.8.8 ]
      routes:
        - to: default
          via: 172.16.0.1
    eth2:
      addresses:
        - 192.168.100.1/24
      routes:
        - to: 192.168.102.0/24
          via: 192.168.100.3
