---
- name: Deploy
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - ../ansible_vars.yml
  tasks:
    # set network
    - name: Copy network
      copy:
        src: ./netplan/netplan.yml
        dest: /etc/netplan/50-vagrant.yaml

    - name: Run network configuration
      command: sudo netplan apply

    - name: Remove default Vagrant route
      command: sudo ip route del default via 10.0.2.2

    - name: Enable IPv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    # install and config
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Config nginx
      template:
        src: ./nginx/default.j2
        dest: /etc/nginx/sites-enabled/default.conf
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted