network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
        - 192.168.100.2/24
      nameservers:
        addresses: [ 8.8.8.8 ]
      routes:
        - to: default
          via: 192.168.100.1
        - to: 192.168.102.0/24
          via: 192.168.100.3
    eth2:
      addresses:
        - 192.168.101.1/24
